project:
  type: website

website:
  title: "From R user to R programmer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pre-reqs.qmd
        text: Prerequisites
      - href: schedule.qmd
        text: Schedule

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

